version: '3' # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir
    ports:
      - 80:80
      - 443:443 #for future ssl traffic
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_data
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: johndoe@genericemail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  ports:
  #    - 8001:80
  #  environment:
  #    - PMA_HOST=db
  #    - PMA_PORT=3306
